INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC201', 'Computer Science I for Majors', 4, 0, 'CScore', '');;
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC202', 'Computer Science IU for Majors', 4, 0, 'CScore', 'CMSC201');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC304', 'Social and Ethical Issues in Information Technology', 3, 1, 'CScore', 'CMSC202');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC486', 'Mobile Telephony Communications', 3, 0, 'Techelec', 'CMSC202');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC484', 'Java Server Technologies', 3, 0, 'Techelec', 'CMSC202');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC457', 'Quantum Computation', 3, 0, 'Techelec', 'CMSC203');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC452', 'Logic for Computer Science', 3, 0, 'Techelec', 'CMSC203');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC451', 'Automata Theory and Formal Languages', 3, 0, 'CSelec Techelec', 'CMSC203');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC203', 'Discrete Structures', 3, 0, 'CScore', 'MATH151');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC313', 'Computer Organization and Assembly Language Programming', 3, 1, 'CScore', 'CMSC202 CMSC203');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC411', 'Computer Architecture', 3, 1, 'CScore', 'CMSC313');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC435', 'Computer Graphics', 3, 0, 'CSelec Techelec', 'CMSC313');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC331', 'Principles of Programming Language', 3, 1, 'CScore', 'CMSC202 CMSC203');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC431', 'Compiler Design Principles', 3, 0, 'CSelec Techelec', 'CMSC331');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC432', 'Object-Oriented Programming Languages and Systems', 3, 0, 'Techelec', 'CMSC331');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC433', 'Scripting Languages', 3, 0, 'Techelec', 'CMSC331');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC473', 'Introduction to Natural Language Processing', 3, 0, 'Techelec', 'CMSC331');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC471', 'Introduction to Artificial Intelligence', 3, 0, 'CSelec Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC493', 'Capstone Games Group Project', 3, 0, 'Techelec', 'CMSC435 CMSC471');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC479', 'Introduction to Robotics', 3, 0, 'Techelec', 'CMSC471');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC478', 'Introduction to Machine Learning', 3, 0, 'Techelec', 'CMSC471');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC477', 'Agent Architectures and Multi-Agent Systems', 3, 0, 'Techelec', 'CMSC471');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC447', 'Software Engineering I', 3, 1, 'CScore', 'CMSC341 CMSC4xx');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC448', 'Software Engineering II', 3, 0, 'Techelec', 'CMSC447');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC427', 'Wearable Computing', 3, 0, 'Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC436', 'Data Visualization', 3, 0, 'Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC437', 'Graphical User Interface Programming', 3, 0, 'Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC441', 'Design and Analysis of Algorithms.', 3, 1, 'CScore', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC443', 'Cryptology', 3, 0, 'Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC453', 'Applied Combinatorics and Graph Theory', 3, 0, 'Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC455', 'Numerical Computations', 3, 0, 'CSelec Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC456', 'Symbolic Computation', 3, 0, 'CSelec Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC476', 'Information Retrieval', 3, 0, 'Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC475', 'Introduction to Neural Networks', 3, 0, 'Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC421', 'Principles of Operating Systems', 3, 1, 'CScore', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC426', 'Principles of Computer Security', 3, 0, 'CSelec Techelec', 'CMSC421');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC483', 'Parallel and Distributed Processing', 3, 0, 'CSelec Techelec', 'CMSC421');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC487', 'Introduction To Network Security', 3, 0, 'Techelec', 'CMSC421 CMSC481');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC465', 'Introduction to Electronic Commerce', 3, 0, 'Techelec', 'CMSC461 CMSC481');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC466', 'Electronic Commerce Technology', 3, 0, 'Techelec', 'CMSC461 CMSC481');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC481', 'Computer Networks', 3, 0, 'CSelec Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC461', 'Database Management Systems', 3, 0, 'CSelec Techelec', 'CMSC341');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC341', 'Data Structures', 3, 1, 'CScore', 'CMSC202 CMSC203');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC291', 'Special Topics in Computer Science', -1, 0, 'otherCS','');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC299', 'Independent Study in Computer Science', -1, 0, 'otherCS', '');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CMSC499', 'Independent Study in Computer Science', -1, 0, 'otherCS', '');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('STAT355', 'Introduction to Probability and Statistics for Scientists and Engineers', 4, 1, 'Reqstat', 'MATH152');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CHEM101', 'Principles of Chemistry I', 4, 0, 'Sci', '');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CHEM102', 'Principles of Chemistry II', 4, 0, 'Sci', 'CHEM101');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('CHEM102L', 'Introductory Chemistry Lab I', 2, 0, 'SciLab', 'CHEM101');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('GES110', 'Physical Geography', 3, 0, 'Sci', '');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('BIOL141', 'Foundations of Biology: Cells, Energy and Organisms', 4, 0, 'Sci', '');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('BIOL142', 'Foundations of Biology: Ecology and Evolution', 4, 0, 'Sci', 'BIOL141');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('SCI100', 'Water; An Interdisciplinary Study (MS)', 3, 0, 'SciLab', '');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('SCI101L', 'Quantitative Reasoning: Measurement and Skills Lab', 2, 0, 'SciLab', '');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('PHYS121', 'Introductory Physics I', 4, 0, 'Sci', '');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('PHYS122', 'Introductory Physics II', 4, 0, 'Sci', 'PHYS121');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('GES286', 'Ecploring the Environment: A Geo-Spatial Perspective', 4, 0, 'SciLab', '');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('PHYS122L', 'Introductory Physics Laboratory', 2, 0, 'SciLab', 'PHYS121');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('MATH251', 'Multivariable Calculus', 4, 0, 'Sci', 'MATH152');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('MATH151', 'Calculus and Analytic Geometry I', 4, 1, 'Reqmath', '');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('MATH152', 'Calculus and Analytic Geometry II', 4, 1, 'Reqmath', 'MATH151');
INSERT INTO `Courses`(`courseID`, `name`, `credits`, `required`, `courseType`, `prereqs`) VALUES ('MATH221', 'Introduction to Linear Algebra', 3, 1, 'Reqmath', 'MATH151');